// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi5FmfcDPiAYVUsdmel9U3nikeX3PGhME',
    appId: '1:92828662084:web:94266d2e2e402fa634ff11',
    messagingSenderId: '92828662084',
    projectId: 'advertisement-bf17e',
    authDomain: 'advertisement-bf17e.firebaseapp.com',
    storageBucket: 'advertisement-bf17e.appspot.com',
    measurementId: 'G-Q6PMQF3Q1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDiR2giyglbMJvvjRhszKpmdLDWT0dOjQ',
    appId: '1:92828662084:android:a1b9494a643bc37634ff11',
    messagingSenderId: '92828662084',
    projectId: 'advertisement-bf17e',
    storageBucket: 'advertisement-bf17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHyQBZTkkMv_VgLscl-N4aiMA0BUAx0f0',
    appId: '1:92828662084:ios:4939b8a85c014ce134ff11',
    messagingSenderId: '92828662084',
    projectId: 'advertisement-bf17e',
    storageBucket: 'advertisement-bf17e.appspot.com',
    iosClientId: '92828662084-ff9r1p09hva08bti01cmoursgjhgvr6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.advertisement',
  );
}
